// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../collection/collection.dart';
import '../connection/connection_config.dart';
import '../connection/tls_type.dart';
import '../connection/tls_types/tls_type_one_way.dart';
import '../connection/tls_types/tls_type_two_way.dart';
import '../environment/environment.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class AppConfig {
  final List<Collection> collections;

  const AppConfig({
    required this.collections,
  });

  static Future<AppConfig> load({required String path}) => RustLib.instance.api
      .crateApiModelsConfigAppConfigAppConfigLoad(path: path);

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<AppConfig> newInstance() =>
      RustLib.instance.api.crateApiModelsConfigAppConfigAppConfigNew();

  @override
  int get hashCode => collections.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is AppConfig &&
          runtimeType == other.runtimeType &&
          collections == other.collections;
}
