// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

String greet({required String name}) =>
    RustLib.instance.api.crateApiSimpleGreet(name: name);

Stream<String> testInvoke(
        {required String serverUrl, required String target}) =>
    RustLib.instance.api
        .crateApiSimpleTestInvoke(serverUrl: serverUrl, target: target);
