// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'tls_type.dart';
import 'tls_types/tls_type_one_way.dart';
import 'tls_types/tls_type_two_way.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class ConnectionConfig {
  final String host;
  final int port;
  final TlsType tlsType;

  const ConnectionConfig({
    required this.host,
    required this.port,
    required this.tlsType,
  });

  @override
  int get hashCode => host.hashCode ^ port.hashCode ^ tlsType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConnectionConfig &&
          runtimeType == other.runtimeType &&
          host == other.host &&
          port == other.port &&
          tlsType == other.tlsType;
}
