// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'tls_types/tls_type_one_way.dart';
import 'tls_types/tls_type_two_way.dart';
part 'tls_type.freezed.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

@freezed
sealed class TlsType with _$TlsType {
  const TlsType._();

  const factory TlsType.plainText() = TlsType_PlainText;
  const factory TlsType.oneWay(
    TlsTypeOneWay field0,
  ) = TlsType_OneWay;
  const factory TlsType.twoWay(
    TlsTypeTwoWay field0,
  ) = TlsType_TwoWay;
}
