// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class ProjectUtilities {
  const ProjectUtilities();

  static String? validateProjectDir({required String dirPath}) => RustLib
      .instance.api
      .crateApiModelsProjectProjectUtilitiesProjectUtilitiesValidateProjectDir(
          dirPath: dirPath);

  @override
  int get hashCode => 0;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ProjectUtilities && runtimeType == other.runtimeType;
}
