// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import '../connection/connection_config.dart';
import '../connection/tls_type.dart';
import '../connection/tls_types/tls_type_one_way.dart';
import '../connection/tls_types/tls_type_two_way.dart';
import '../environment/environment.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `fmt`

class Collection {
  final String id;
  final String displayName;
  final List<Environment> environments;
  final String? iconPath;

  const Collection({
    required this.id,
    required this.displayName,
    required this.environments,
    this.iconPath,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      displayName.hashCode ^
      environments.hashCode ^
      iconPath.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Collection &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          displayName == other.displayName &&
          environments == other.environments &&
          iconPath == other.iconPath;
}
