// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `fmt`, `fmt`, `from`, `from`

class EnumDescriptor {
  final List<EnumValueDescriptor> values;

  const EnumDescriptor({
    required this.values,
  });

  @override
  int get hashCode => values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumDescriptor &&
          runtimeType == other.runtimeType &&
          values == other.values;
}

class EnumValueDescriptor {
  final String name;
  final int index;

  const EnumValueDescriptor({
    required this.name,
    required this.index,
  });

  @override
  int get hashCode => name.hashCode ^ index.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is EnumValueDescriptor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index;
}
