// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'enum_descriptor.dart';
import 'field_type_descriptor.dart';
import 'message_descriptor.dart';
import 'oneof_descriptor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

class FieldDescriptor {
  final String name;
  final int index;
  final FieldTypeDescriptor fieldType;
  final bool isRepeated;

  const FieldDescriptor({
    required this.name,
    required this.index,
    required this.fieldType,
    required this.isRepeated,
  });

  @override
  int get hashCode =>
      name.hashCode ^ index.hashCode ^ fieldType.hashCode ^ isRepeated.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FieldDescriptor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          index == other.index &&
          fieldType == other.fieldType &&
          isRepeated == other.isRepeated;
}
