// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.1.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../../frb_generated.dart';
import 'enum_descriptor.dart';
import 'field_descriptor.dart';
import 'field_type_descriptor.dart';
import 'message_descriptor.dart';
import 'oneof_descriptor.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`, `from`

class MethodDescriptor {
  final String name;
  final String fullName;
  final String parentServiceName;
  final MessageDescriptor input;
  final MessageDescriptor output;
  final bool isServerStreaming;

  const MethodDescriptor({
    required this.name,
    required this.fullName,
    required this.parentServiceName,
    required this.input,
    required this.output,
    required this.isServerStreaming,
  });

  String target() => RustLib.instance.api
          .crateApiModelsDescriptorsMethodDescriptorMethodDescriptorTarget(
        that: this,
      );

  @override
  int get hashCode =>
      name.hashCode ^
      fullName.hashCode ^
      parentServiceName.hashCode ^
      input.hashCode ^
      output.hashCode ^
      isServerStreaming.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is MethodDescriptor &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          fullName == other.fullName &&
          parentServiceName == other.parentServiceName &&
          input == other.input &&
          output == other.output &&
          isServerStreaming == other.isServerStreaming;
}
